/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogoDaVelha;

import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class VelhaTela extends javax.swing.JFrame {
    Velha velha = new Velha();
    String jogadas1, jogadas2;

    /**
     * Creates new form JogoDaVelhaTela
     */
    public VelhaTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel8 = new javax.swing.JLabel();
        labelJogador1 = new javax.swing.JLabel();
        labelJogador2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNomeJogador1 = new javax.swing.JTextField();
        campoNomeJogador2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botaoIniciarPartida = new javax.swing.JButton();
        campoSimboloJogador2 = new javax.swing.JTextField();
        BotaoVelhaCampo1 = new javax.swing.JButton();
        BotaoVelhaCampo2 = new javax.swing.JButton();
        BotaoVelhaCampo3 = new javax.swing.JButton();
        BotaoVelhaCampo4 = new javax.swing.JButton();
        BotaoVelhaCampo5 = new javax.swing.JButton();
        BotaoVelhaCampo6 = new javax.swing.JButton();
        BotaoVelhaCampo7 = new javax.swing.JButton();
        BotaoVelhaCampo8 = new javax.swing.JButton();
        BotaoVelhaCampo9 = new javax.swing.JButton();
        botaoFinalizarPartida = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoSimboloJogador1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJogador1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelJogador1.setText("Jogador 1:");

        labelJogador2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelJogador2.setText("Jogador 2:");

        jLabel1.setText("Nome do Jogador 1:");

        jLabel2.setText("Nome do Jogador 2:");

        jLabel3.setText("Símbolo do Jogador 1:");

        jLabel4.setText("Símbolo do Jogador 2:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Jogo da Velha");

        botaoIniciarPartida.setText("Iniciar Partida");
        botaoIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarPartidaActionPerformed(evt);
            }
        });

        BotaoVelhaCampo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo1.setText("  ");
        BotaoVelhaCampo1.setEnabled(false);
        BotaoVelhaCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo1ActionPerformed(evt);
            }
        });

        BotaoVelhaCampo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo2.setText("  ");
        BotaoVelhaCampo2.setEnabled(false);
        BotaoVelhaCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo2ActionPerformed(evt);
            }
        });

        BotaoVelhaCampo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo3.setText("  ");
        BotaoVelhaCampo3.setEnabled(false);
        BotaoVelhaCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo3ActionPerformed(evt);
            }
        });

        BotaoVelhaCampo4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo4.setText("  ");
        BotaoVelhaCampo4.setEnabled(false);
        BotaoVelhaCampo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo4ActionPerformed(evt);
            }
        });

        BotaoVelhaCampo5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo5.setText("  ");
        BotaoVelhaCampo5.setEnabled(false);
        BotaoVelhaCampo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo5ActionPerformed(evt);
            }
        });

        BotaoVelhaCampo6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo6.setText("  ");
        BotaoVelhaCampo6.setEnabled(false);
        BotaoVelhaCampo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo6ActionPerformed(evt);
            }
        });

        BotaoVelhaCampo7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo7.setText("  ");
        BotaoVelhaCampo7.setEnabled(false);
        BotaoVelhaCampo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo7ActionPerformed(evt);
            }
        });

        BotaoVelhaCampo8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo8.setText("  ");
        BotaoVelhaCampo8.setEnabled(false);
        BotaoVelhaCampo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo8ActionPerformed(evt);
            }
        });

        BotaoVelhaCampo9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotaoVelhaCampo9.setText("  ");
        BotaoVelhaCampo9.setEnabled(false);
        BotaoVelhaCampo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVelhaCampo9ActionPerformed(evt);
            }
        });

        botaoFinalizarPartida.setText("Finalizar Partida");
        botaoFinalizarPartida.setEnabled(false);
        botaoFinalizarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarPartidaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Partida");

        jLabel7.setText("(clique no botão referênte à posição que deseja jogar)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoFinalizarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoVelhaCampo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoVelhaCampo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoVelhaCampo3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoVelhaCampo4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoVelhaCampo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoVelhaCampo6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoVelhaCampo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoVelhaCampo8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoVelhaCampo9))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(campoNomeJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoSimboloJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(campoNomeJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoSimboloJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(labelJogador1)
                    .addComponent(labelJogador2)
                    .addComponent(jLabel5)
                    .addComponent(botaoIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(labelJogador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNomeJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(campoSimboloJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(labelJogador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNomeJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(campoSimboloJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(botaoIniciarPartida)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoVelhaCampo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoVelhaCampo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoVelhaCampo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoVelhaCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotaoVelhaCampo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoVelhaCampo6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoVelhaCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoVelhaCampo8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoVelhaCampo9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoFinalizarPartida)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVelhaCampo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo6ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo6.setText(campoSimboloJogador1.getText());
            jogadas1+="6";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());
        }else{
            BotaoVelhaCampo6.setText(campoSimboloJogador2.getText());
            jogadas2+="6";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());
        }
        BotaoVelhaCampo6.setEnabled(false);
    }//GEN-LAST:event_BotaoVelhaCampo6ActionPerformed

    private void BotaoVelhaCampo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo7ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo7.setText(campoSimboloJogador1.getText());
            jogadas1+="7";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());
        }else{
            BotaoVelhaCampo7.setText(campoSimboloJogador2.getText());
            jogadas2+="7";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());
        }
        BotaoVelhaCampo7.setEnabled(false);
    }//GEN-LAST:event_BotaoVelhaCampo7ActionPerformed

    private void BotaoVelhaCampo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo8ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo8.setText(campoSimboloJogador1.getText());
            jogadas1+="8";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());
        }else{
            BotaoVelhaCampo8.setText(campoSimboloJogador2.getText());
            jogadas2+="8";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());
        }
        BotaoVelhaCampo8.setEnabled(false);
    }//GEN-LAST:event_BotaoVelhaCampo8ActionPerformed

    private void BotaoVelhaCampo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo9ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo9.setText(campoSimboloJogador1.getText());
            jogadas1+="9";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());
        }else{
            BotaoVelhaCampo9.setText(campoSimboloJogador2.getText());
            jogadas2+="9";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());

        }
        BotaoVelhaCampo9.setEnabled(false);
    }//GEN-LAST:event_BotaoVelhaCampo9ActionPerformed

    private void botaoIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarPartidaActionPerformed
        jogadas1="";
        jogadas2=""; 
        Velha velha = new Velha();
        
        if((campoSimboloJogador1.getText().length()!=1 || campoSimboloJogador2.getText().length()!=1) || (campoSimboloJogador1.getText().isEmpty() || campoSimboloJogador2.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Símbolo(s) inválido(s)!Os símbolos dos jogadores devem ter um, e apenas um caractere!" ,"Erro",JOptionPane.ERROR_MESSAGE);
        }else if((campoNomeJogador1.getText().isEmpty() || campoNomeJogador2.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Insira os nomes dos jogadores 1 e 2!" ,"Erro",JOptionPane.ERROR_MESSAGE);
        }  
        else if(campoSimboloJogador1.getText().equals(campoSimboloJogador2.getText())){
            JOptionPane.showMessageDialog(null, "Os símbolos dos jogadores devem ser diferentes!");  
        }else{
            velha.iniciarPartida(campoNomeJogador1.toString(), campoNomeJogador2.toString(), campoSimboloJogador1.toString(), campoSimboloJogador2.toString());            
            JOptionPane.showMessageDialog(null, "Jogador(a) "+campoNomeJogador1.getText()+" começa jogando!");
        }
    }//GEN-LAST:event_botaoIniciarPartidaActionPerformed

    private void BotaoVelhaCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo1ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo1.setText(campoSimboloJogador1.getText());
            jogadas1+="1";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());
        }else{
            BotaoVelhaCampo1.setText(campoSimboloJogador2.getText());
            jogadas2+="1";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());
        }
        BotaoVelhaCampo1.setEnabled(false);      
    }//GEN-LAST:event_BotaoVelhaCampo1ActionPerformed

    private void BotaoVelhaCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo2ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo2.setText(campoSimboloJogador1.getText());
            jogadas1+="2";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());

        }else{
            BotaoVelhaCampo2.setText(campoSimboloJogador2.getText());
            jogadas2+="2";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());
        }
        BotaoVelhaCampo2.setEnabled(false);
    }//GEN-LAST:event_BotaoVelhaCampo2ActionPerformed

    private void BotaoVelhaCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo3ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo3.setText(campoSimboloJogador1.getText());
            jogadas1+="3";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());

        }else{
            BotaoVelhaCampo3.setText(campoSimboloJogador2.getText());
            jogadas2+="3";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());
        }
        BotaoVelhaCampo3.setEnabled(false);
    }//GEN-LAST:event_BotaoVelhaCampo3ActionPerformed

    private void BotaoVelhaCampo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo4ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo4.setText(campoSimboloJogador1.getText());
            jogadas1+="4";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());
        }else{
            BotaoVelhaCampo4.setText(campoSimboloJogador2.getText());
            jogadas2+="4";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());
        }
        BotaoVelhaCampo4.setEnabled(false);

    }//GEN-LAST:event_BotaoVelhaCampo4ActionPerformed

    private void BotaoVelhaCampo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVelhaCampo5ActionPerformed
        if(velha.passarTurno()%2==1){
            BotaoVelhaCampo5.setText(campoSimboloJogador1.getText());
            jogadas1+="5";
            velha.verificarResultado(jogadas1, campoNomeJogador1.getText());
        }else{
            BotaoVelhaCampo5.setText(campoSimboloJogador2.getText());
            jogadas2+="5";
            velha.verificarResultado(jogadas2, campoNomeJogador2.getText());
        }
        BotaoVelhaCampo5.setEnabled(false);
    }//GEN-LAST:event_BotaoVelhaCampo5ActionPerformed

    private void botaoFinalizarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarPartidaActionPerformed
        velha.finalizarPartida();
    }//GEN-LAST:event_botaoFinalizarPartidaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelhaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelhaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelhaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelhaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VelhaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BotaoVelhaCampo1;
    public static javax.swing.JButton BotaoVelhaCampo2;
    public static javax.swing.JButton BotaoVelhaCampo3;
    public static javax.swing.JButton BotaoVelhaCampo4;
    public static javax.swing.JButton BotaoVelhaCampo5;
    public static javax.swing.JButton BotaoVelhaCampo6;
    public static javax.swing.JButton BotaoVelhaCampo7;
    public static javax.swing.JButton BotaoVelhaCampo8;
    public static javax.swing.JButton BotaoVelhaCampo9;
    public static javax.swing.JButton botaoFinalizarPartida;
    public static javax.swing.JButton botaoIniciarPartida;
    public static javax.swing.JTextField campoNomeJogador1;
    public static javax.swing.JTextField campoNomeJogador2;
    public static javax.swing.JTextField campoSimboloJogador1;
    public static javax.swing.JTextField campoSimboloJogador2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel labelJogador1;
    private javax.swing.JLabel labelJogador2;
    // End of variables declaration//GEN-END:variables
}
